# Generated by Django 5.0.4 on 2024-05-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
